import { Script } from './types';

export const guionBase: Script[] = [
  // --- GUIONES ACTIVOS (Muestra) ---
  {
    "id": "act-1",
    "title": "JOSÉ MARTÍ Y SU ENTORNO FAMILIAR",
    "genre": "BUENOS DÍAS BAYAMO",
    "summary": "Archivo: BDB 28 de enero de 2025.doc",
    "themes": ["JOSÉ", "MARTÍ", "FAMILIA", "HISTORIA"],
    "tone": "Informativo",
    "dateAdded": "2025-01-28T10:00:00Z",
    "status": "active",
    "wordCount": 150,
    "content": "1. PROGRAMA:BUENOS DÍAS BAYAMO\nArchivo: BDB 28 de enero de 2025.doc\nFecha: SÁBADO 28 DE ENERO DE 2025\nTema: JOSÉ MARTÍ Y SU ENTORNO FAMILIAR"
  },
  {
    "id": "act-2",
    "title": "CONVERSANDO CON IDANIS ORTIZ",
    "genre": "AL SON DE LA RADIO",
    "summary": "Archivo: ASR 19 DE JULIO 2025.doc",
    "themes": ["ENTREVISTA", "IDANIS", "ORTIZ", "DEPORTE", "JUDO"],
    "tone": "Entrevista",
    "dateAdded": "2025-07-19T10:00:00Z",
    "status": "active",
    "wordCount": 200,
    "content": "2. PROGRAMA: AL SON DE LA RADIO\nArchivo: ASR 19 DE JULIO 2025.doc\nFecha: 19 DE JULIO DE 2025\nTema: CONVERSANDO CON IDANIS ORTIZ"
  },
  {
    "id": "act-3",
    "title": "SEXTETOS Y SEPTETOS EN LA MÚSICA CUBANA",
    "genre": "AL SON DE LA RADIO",
    "summary": "Archivo: ASR 12 DE JULIO 2025.doc",
    "themes": ["MÚSICA", "CUBANA", "SEXTETOS", "SEPTETOS", "TRADICIÓN"],
    "tone": "Cultural",
    "dateAdded": "2025-07-12T10:00:00Z",
    "status": "active",
    "wordCount": 180,
    "content": "3. PROGRAMA: AL SON DE LA RADIO\nArchivo: ASR 12 DE JULIO 2025.doc\nFecha: 12 DE JULIO DE 2025\nTema: SEXTETOS Y SEPTETOS EN LA MÚSICA CUBANA"
  },
  {
    "id": "act-4",
    "title": "EL SON EN EL CINE CUBANO",
    "genre": "AL SON DE LA RADIO",
    "summary": "Archivo: ASR 26 DE JULIO 2025.doc",
    "themes": ["CINE", "SON", "CULTURA", "DOCUMENTAL"],
    "tone": "Cultural",
    "dateAdded": "2025-07-26T10:00:00Z",
    "status": "active",
    "wordCount": 190,
    "content": "4. PROGRAMA: AL SON DE LA RADIO\nArchivo: ASR 26 DE JULIO 2025.doc\nFecha: 26 DE JULIO DE 2025\nTema: EL SON EN EL CINE CUBANO"
  },
  {
    "id": "act-5",
    "title": "CARLOS PUEBLA, CANTOR DE LA REVOLUCIÓN",
    "genre": "AL SON DE LA RADIO",
    "summary": "Archivo: ASR 20 DE SEPTIEMBRE 2025.doc",
    "themes": ["MÚSICA", "HISTORIA", "REVOLUCIÓN", "TROVA"],
    "tone": "Homenaje",
    "dateAdded": "2025-09-20T10:00:00Z",
    "status": "active",
    "wordCount": 160,
    "content": "5. PROGRAMA: AL SON DE LA RADIO\nArchivo: ASR 20 DE SEPTIEMBRE 2025.doc\nFecha: 20 DE SEPTIEMBRE DE 2025\nTema: CARLOS PUEBLA, CANTOR DE LA REVOLUCIÓN"
  },
  {
    "id": "act-6",
    "title": "JOSEÍTO FERNÁNDEZ, MÁS ALLÁ DE LA GUANTANAMERA",
    "genre": "AL SON DE LA RADIO",
    "summary": "Archivo: ASR 06 DE SEPTIEMBRE 2025.doc",
    "themes": ["MÚSICA", "GUAJIRA", "JOSEÍTO", "FERNÁNDEZ"],
    "tone": "Biográfico",
    "dateAdded": "2025-09-06T10:00:00Z",
    "status": "active",
    "wordCount": 170,
    "content": "6. PROGRAMA: AL SON DE LA RADIO\nArchivo: ASR 06 DE SEPTIEMBRE 2025.doc\nFecha: 06 DE SEPTIEMBRE DE 2025\nTema: JOSEÍTO FERNÁNDEZ, MÁS ALLÁ DE LA GUANTANAMERA"
  },
  {
    "id": "act-7",
    "title": "EL COMPLEJO GENÉRICO DEL SON",
    "genre": "AL SON DE LA RADIO",
    "summary": "Archivo: ASR 05 DE JULIO 2025.doc",
    "themes": ["MÚSICA", "SON", "TEORÍA", "GÉNEROS"],
    "tone": "Educativo",
    "dateAdded": "2025-07-05T10:00:00Z",
    "status": "active",
    "wordCount": 180,
    "content": "7. PROGRAMA: AL SON DE LA RADIO\nArchivo: ASR 05 DE JULIO 2025.doc\nFecha: 05 DE JULIO DE 2025\nTema: EL COMPLEJO GENÉRICO DEL SON"
  },
  {
    "id": "act-8",
    "title": "SON CUBANO PARA EL CARNAVAL",
    "genre": "AL SON DE LA RADIO",
    "summary": "Archivo: ASR 09 DE AGOSTO 2025.doc",
    "themes": ["CARNAVAL", "FIESTA", "TRADICIÓN", "BAILE"],
    "tone": "Festivo",
    "dateAdded": "2025-08-09T10:00:00Z",
    "status": "active",
    "wordCount": 160,
    "content": "8. PROGRAMA: AL SON DE LA RADIO\nArchivo: ASR 09 DE AGOSTO 2025.doc\nFecha: 09 DE AGOSTO DE 2025\nTema: SON CUBANO PARA EL CARNAVAL"
  },
  {
    "id": "act-9",
    "title": "LOS VAN VAN",
    "genre": "AL SON DE LA RADIO",
    "summary": "Archivo: ASR 02 DE AGOSTO 2025.doc",
    "themes": ["VAN VAN", "TIMBA", "ORQUESTA", "BAILE"],
    "tone": "Musical",
    "dateAdded": "2025-08-02T10:00:00Z",
    "status": "active",
    "wordCount": 170,
    "content": "9. PROGRAMA: AL SON DE LA RADIO\nArchivo: ASR 02 DE AGOSTO 2025.doc\nFecha: 02 DE AGOSTO DE 2025\nTema: LOS VAN VAN"
  },
  {
    "id": "act-10",
    "title": "LA TIMBA",
    "genre": "AL SON DE LA RADIO",
    "summary": "Archivo: ASR 16 DE AGOSTO 2025.doc",
    "themes": ["TIMBA", "MÚSICA", "POPULAR", "BAILABLE"],
    "tone": "Informativo",
    "dateAdded": "2025-08-16T10:00:00Z",
    "status": "active",
    "wordCount": 160,
    "content": "10. PROGRAMA: AL SON DE LA RADIO\nArchivo: ASR 16 DE AGOSTO 2025.doc\nFecha: 16 DE AGOSTO DE 2025\nTema: LA TIMBA"
  },
  {
    "id": "act-25",
    "title": "PRILIDIANO PUEYRREDÓN, PINTOR Y ARQUITECTO ARGENTINO",
    "genre": "ARTE BAYAMO",
    "summary": "Archivo: AB 28 de Mayo 2024.doc",
    "themes": ["PINTURA", "ARQUITECTURA", "ARGENTINA", "HISTORIA"],
    "tone": "Biográfico",
    "dateAdded": "2024-05-28T10:00:00Z",
    "status": "active",
    "wordCount": 150,
    "content": "25. PROGRAMA: ARTE BAYAMO\nArchivo: AB 28 de Mayo 2024.doc\nFecha: MARTES 28 DE MAYO DE 2024\nTema: PRILIDIANO PUEYRREDÓN, PINTOR Y ARQUITECTO ARGENTINO"
  },
  {
    "id": "act-26",
    "title": "FESTIVAL ISLA VERDE, SOBRE EL CINE DEDICADO AL MEDIO AMBIENTE",
    "genre": "ARTE BAYAMO",
    "summary": "Archivo: AB 26 de Mayo.doc",
    "themes": ["CINE", "MEDIO AMBIENTE", "FESTIVAL", "ECOLOGÍA"],
    "tone": "Informativo",
    "dateAdded": "2025-05-26T10:00:00Z",
    "status": "active",
    "wordCount": 160,
    "content": "26. PROGRAMA: ARTE BAYAMO\nArchivo: AB 26 de Mayo.doc\nFecha: LUNES 26 DE MAYO DE 2025\nTema: FESTIVAL ISLA VERDE, SOBRE EL CINE DEDICADO AL MEDIO AMBIENTE"
  },
  {
    "id": "act-27",
    "title": "NELSON DOMÍNGUEZ, PINTOR CUBANO",
    "genre": "ARTE BAYAMO",
    "summary": "Archivo: AB 21 de Mayo 2024.doc",
    "themes": ["PINTURA", "CUBANA", "NELSON", "DOMÍNGUEZ"],
    "tone": "Biográfico",
    "dateAdded": "2024-05-21T10:00:00Z",
    "status": "active",
    "wordCount": 150,
    "content": "27. PROGRAMA: ARTE BAYAMO\nArchivo: AB 21 de Mayo 2024.doc\nFecha: MARTES 21 DE MAYO DE 2024\nTema: NELSON DOMÍNGUEZ, PINTOR CUBANO"
  },
  {
    "id": "act-33",
    "title": "UN RECORRIDO POR EL MUSEO DEL LOUVRE EN PARIS",
    "genre": "ARTE BAYAMO",
    "summary": "Archivo: AB 5 de Marzo 2024.doc",
    "themes": ["MUSEO", "LOUVRE", "PARIS", "ARTE UNIVERSAL"],
    "tone": "Cultural",
    "dateAdded": "2024-03-05T10:00:00Z",
    "status": "active",
    "wordCount": 170,
    "content": "33. PROGRAMA: ARTE BAYAMO\nArchivo: AB 5 de Marzo 2024.doc\nFecha: MARTES 5 DE MARZO DE 2024\nTema: UN RECORRIDO POR EL MUSEO DEL LOUVRE EN PARIS"
  },
  {
    "id": "act-36",
    "title": "LA PELÍCULA CUBANA “FRESA Y CHOCOLATE”",
    "genre": "ARTE BAYAMO",
    "summary": "Archivo: AB 4 de Marzo 2024.doc",
    "themes": ["CINE", "CUBA", "CLÁSICO", "CULTURA"],
    "tone": "Crítica",
    "dateAdded": "2024-03-04T10:00:00Z",
    "status": "active",
    "wordCount": 160,
    "content": "36. PROGRAMA: ARTE BAYAMO\nArchivo: AB 4 de Marzo 2024.doc\nFecha: LUNES 4 DE MARZO DE 2024\nTema: LA PELÍCULA CUBANA “FRESA Y CHOCOLATE”"
  },
  
  // --- GUIONES INACTIVOS (Muestra) ---
  {
    "id": "inact-1",
    "title": "LA FUSIÓN EN LA MÚSICA CUBANA",
    "genre": "COMBINACIÓN SONORA",
    "summary": "Archivo: CS 2 DE SEPTIEMBRE.doc",
    "themes": ["FUSIÓN", "MÚSICA", "CUBANA", "MEZCLA"],
    "tone": "Informativo",
    "dateAdded": "2023-09-02T10:00:00Z",
    "status": "inactive",
    "wordCount": 150,
    "content": "1. PROGRAMA: COMBINACIÓN SONORA\nArchivo: CS 2 DE SEPTIEMBRE.doc\nFecha: SÁBADO 2 DE SEPTIEMBRE DE 2023\nTema: LA FUSIÓN EN LA MÚSICA CUBANA"
  },
  {
    "id": "inact-2",
    "title": "OBRA Y LEGADO DE CÉSAR PORTILLO DE LA LUZ",
    "genre": "COMBINACIÓN SONORA",
    "summary": "Archivo: CS 22 DE JULIIO.doc",
    "themes": ["FILIN", "BOLERO", "CÉSAR", "PORTILLO"],
    "tone": "Homenaje",
    "dateAdded": "2023-07-22T10:00:00Z",
    "status": "inactive",
    "wordCount": 160,
    "content": "2. PROGRAMA: COMBINACIÓN SONORA\nArchivo: CS 22 DE JULIIO.doc\nFecha: SÁBADO 22 DE JULIO DE 2023\nTema: OBRA Y LEGADO DE CÉSAR PORTILLO DE LA LUZ"
  },
  {
    "id": "inact-3",
    "title": "SEXTETOS Y SEPTETOS EN LA MÚSICA CUBANA",
    "genre": "COMBINACIÓN SONORA",
    "summary": "Archivo: CS 19 DE AGOSTO.doc",
    "themes": ["SEXTETOS", "SEPTETOS", "TRADICIÓN", "SON"],
    "tone": "Educativo",
    "dateAdded": "2023-08-19T10:00:00Z",
    "status": "inactive",
    "wordCount": 150,
    "content": "3. PROGRAMA: COMBINACIÓN SONORA\nArchivo: CS 19 DE AGOSTO.doc\nFecha: SÁBADO 19 DE AGOSTO DE 2023\nTema: SEXTETOS Y SEPTETOS EN LA MÚSICA CUBANA"
  },
  {
    "id": "inact-4",
    "title": "EL CHACHACHÁ",
    "genre": "COMBINACIÓN SONORA",
    "summary": "Archivo: CS 12 DE AGOSTO.doc",
    "themes": ["CHACHACHÁ", "BAILE", "MÚSICA", "JORRÍN"],
    "tone": "Musical",
    "dateAdded": "2023-08-12T10:00:00Z",
    "status": "inactive",
    "wordCount": 140,
    "content": "4. PROGRAMA: COMBINACIÓN SONORA\nArchivo: CS 12 DE AGOSTO.doc\nFecha: SÁBADO 12 DE AGOSTO DE 2023\nTema: EL CHACHACHÁ"
  },
  {
    "id": "inact-5",
    "title": "EL FORMATO CHARANGA EN LA MÚSICA CUBANA",
    "genre": "COMBINACIÓN SONORA",
    "summary": "Archivo: CS 15 DE JULIIO.doc",
    "themes": ["CHARANGA", "FORMATO", "ORQUESTA", "FLAUTA"],
    "tone": "Técnico",
    "dateAdded": "2023-07-15T10:00:00Z",
    "status": "inactive",
    "wordCount": 150,
    "content": "5. PROGRAMA: COMBINACIÓN SONORA\nArchivo: CS 15 DE JULIIO.doc\nFecha: SÁBADO 15 DE JULIO DE 2023\nTema: EL FORMATO CHARANGA EN LA MÚSICA CUBANA"
  },
  {
    "id": "inact-6",
    "title": "LA TIMBA",
    "genre": "COMBINACIÓN SONORA",
    "summary": "Archivo: CS 5 DE AGOSTO.doc",
    "themes": ["TIMBA", "MODERNIDAD", "BAILE", "CUBANO"],
    "tone": "Informativo",
    "dateAdded": "2023-08-05T10:00:00Z",
    "status": "inactive",
    "wordCount": 150,
    "content": "6. PROGRAMA: COMBINACIÓN SONORA\nArchivo: CS 5 DE AGOSTO.doc\nFecha: SÁBADO 5 DE AGOSTO DE 2023\nTema: LA TIMBA"
  },
  {
    "id": "inact-12",
    "title": "GABRIEL CASTRO PANTOJA, ESCRITOR",
    "genre": "CRECIENDO",
    "summary": "Archivo: CC 12 de agosto.doc",
    "themes": ["LITERATURA", "ESCRITOR", "GABRIEL", "CASTRO"],
    "tone": "Entrevista",
    "dateAdded": "2023-08-12T10:00:00Z",
    "status": "inactive",
    "wordCount": 140,
    "content": "12. PROGRAMA: CRECIENDO\nArchivo: CC 12 de agosto.doc\nFecha: 12 DE AGOSTO DE 2023\nTema: GABRIEL CASTRO PANTOJA, ESCRITOR"
  },
  {
    "id": "inact-13",
    "title": "LISBET GONZÁLEZ TEJEDA, ACTRIZ DE LA COMPAÑÍA TIEMPO",
    "genre": "CRECIENDO",
    "summary": "Archivo: CC 5 de agosto.doc",
    "themes": ["ACTUACIÓN", "TEATRO", "COMPAÑÍA TIEMPO"],
    "tone": "Entrevista",
    "dateAdded": "2023-08-05T10:00:00Z",
    "status": "inactive",
    "wordCount": 150,
    "content": "13. PROGRAMA: CRECIENDO\nArchivo: CC 5 de agosto.doc\nFecha: 5 DE AGOSTO DE 2023\nTema: LISBET GONZÁLEZ TEJEDA, ACTRIZ DE LA COMPAÑÍA TIEMPO"
  },
  {
    "id": "inact-18",
    "title": "JAVIEL YERO RAMÍREZ, JOVEN INSTRUCTOR DE ARTES VISUALES",
    "genre": "CRECIENDO",
    "summary": "Archivo: CC 2 de septiembre.doc",
    "themes": ["ARTES VISUALES", "INSTRUCTOR", "JUVENTUD"],
    "tone": "Perfil",
    "dateAdded": "2023-09-02T10:00:00Z",
    "status": "inactive",
    "wordCount": 160,
    "content": "18. PROGRAMA: CRECIENDO\nArchivo: CC 2 de septiembre.doc\nFecha: 2 DE SEPTIEMBRE DE 2023\nTema: JAVIEL YERO RAMÍREZ, JOVEN INSTRUCTOR DE ARTES VISUALES"
  },
  {
    "id": "inact-204",
    "title": "MAGIC, EL REENCUENTRO. UN JUEGO ESPECTACULAR",
    "genre": "PARADA JOVEN",
    "summary": "Archivo: PJ 7 abril.doc",
    "themes": ["MAGIC", "JUEGOS", "ENTRETENIMIENTO", "JUVENTUD"],
    "tone": "Lúdico",
    "dateAdded": "2023-04-07T10:00:00Z",
    "status": "inactive",
    "wordCount": 130,
    "content": "204. PROGRAMA: PARADA JOVEN\nArchivo: PJ 7 abril.doc\nFecha: VIERNES 7 DE ABRIL DE 2023\nTema: MAGIC, EL REENCUENTRO. UN JUEGO ESPECTACULAR"
  }
];
